name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

permissions: {}

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@f05501e212c51ca46626f95da79703182bcfdc6b  # main from 2025-09-05
    with:
      commit_sha: ${{ github.sha }}
      package: peft
      notebook_folder: peft_docs
      custom_container: huggingface/transformers-doc-builder
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
